### ISSUE TITLE
navbar no longer valid

### ISSUE THREAD

**Issue by briancolfer** [wndxgroup/swapi-potion#1]
I am trying to get cloned  swapi-potion example for your RubyMotion Jumpstart to work.  I set my version of ruby to be 2.3.7 installed bundler, did a bundle update.  When I run rake I get the simulator when I navigate to Films I get 
`"set_attribute: #<FilmsScreen:0x1150092d0> does not respond to navbar=."`

**Comment by wndxlori** [comment]
The navbar issue is fixed now.
